Scanners/Series/Absolute Series Scanner.py

Scanner was crashing due to Plex App support path being resolved to st ubuntu ie /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs
UnRaid plugin for PMS allows custom placement of the config folder.
The Env var resolves to the custom position correctly
see https://support.plex.tv/hc/en-us/articles/201105343-Advanced-Server-Settings
for folders this ENV VAR resolves to.

Fix Logs path on custom app support folder location

---

Scanners/Series/Absolute Series Scanner.py

Update to 'clean_string' to swap out text so it will not be filtered
=> Used to create a non-filterable special ep number (EX: 13.5 -> 13DoNoTfIlTeR5)
Update to main loop 'for word in words' to add in tests for these special episode numbers
=> ep 12.5 = "12" title "Special 12.5"
=> ep EP12.5 = "12" title "Special 12.5"

Update to re-add the parsing of dot episodes

---

README.md

It was referring to the page, not the raw download path

Fix scanner download command in example script

---

Scanners/Series/Absolute Series Scanner.py

Needed this for my freenas jails, which returns freebsd9 as platform and without this the log files ended up in:
'/usr/local/plexdata/Plex Media Server/'

Added freebsd9 as platform in log path

---

Scanners/Series/Absolute Series Scanner.py

The problem  is root for linux is '/' but Windows is 'X:\' where X is the drive letter.
So the while loop will never be false and loop forever.
The cleanest solution I could come up with was to use [os.path.splitdrive](https://docs.python.org/2/library/os.path.html#os.path.splitdrive)
Here are some simple tests I ran using Python interactive console
Windows:
```
>>> os.path.splitdrive("S:\\Anime\\Gundam_00")
('S:', '\\Anime\\Gundam_00')
>>> os.path.splitdrive("S:\\")
('S:', '\\')
```
Linux:
```
>>> os.path.splitdrive("/mnt/Anime/Gundam_00")
('', '/mnt/Anime/Gundam_00')
>>> os.path.splitdrive("/")
('', '/')
```
Also you can't use `is` or `is not` when the two are of different type. It worked fine before with string comparison. See example below:
Windows:
```
>>> "\\" is not "\\"
False
"\\" …
```

Fix infinite loop issue when using anidb2 on Windows

---

anime-list-corrections.xml

@ZeroQI, please peer review. All removed are already persisted in Scudlee
https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list-master.xml
Note that some of the 'mapping-list' in this file are also direct duplication of the 'defaulttvdbseason' / 'episodeoffset' values and redundant. So might not be exactly seen in Scudlee's file.
EX:
```
<anime anidbid="11637" tvdbid="293088" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
<name>One Punch Man: Road to Hero</name>
<mapping-list>
<mapping anidbseason="1" tvdbseason="0">;1-1;</mapping>
</mapping-list>
</anime>
```

Removal of persisted Scudlee changes

---

Scanners/Series/Absolute Series Scanner (legacy).py

If Season and Episode are seperated by a dot the episode was only catched in the 2nd episode group.
Furthermore when trying to match obscure stuff like s01-e01 and "s01 e01" the current implementation grouped all episodes in 1 Special episode. This should fix that.
Suggestions for Tests:
Dragon.Ball.Super.S01-E02.HD.ENG.SUBBED.mp4
Series.Title.S01.E02.1080p.mp4
Series Title S01 E01 1080p.mp4
Series Title S01 E01-03 1080p.mp4
Series Title S01 E01-E03 1080p.mp4
Signed-off-by: Robin Wenzel info@robin-wenzel.de

add regex group for additional match in legacy scanner

---

Scanners/Series/Absolute Series Scanner.py

Related to https://github.com/ZeroQI/Hama.bundle/issues/42 and others.
I needed this to quickly test and use the plug-in with a docker image without having to store the token on it. So I just add the option as a fallback option.

Add environment variable X_PLEX_TOKEN as a secondary conf option

---

Scanners/Series/Shell Update scanner.sh

- Added "!" after "#" (with this now shebang really works).
- Changed to "/usr/bin/env sh" in order to extend compatibility to non Linux environments.

Fix shebang on shell updater

---

Scanners/Series/Absolute Series Scanner.py

**Hey @ZeroQI,**
So.....in the work of updating my anime entries over to 'anidb2' mode setup to combine related series animes, I was hit with an issue on multiple TVDB series setups.
The issue was that TVDB had some sequel/prequel entries annoyingly listed as season 0 specials.
I started to try and write custom ScudLee mapping for each I was seeing to move them out of season 0. But I found too many and was concerned I might be missing some (I was). So I have now codded it into the scanner to fix these entries automatically as mode 'anidb3'.
----
**NOTE**: AniDB series that are prequels to the series that is mapped to TVDB season 1 will stay as specials.
**NOTE**: Episode metadata will be blank for those adjusted series episodes till HAMA is updated to handle this new mode.
In AniDB its …

Major Update: Addition of 'anidb3' & 'anidb4' mode

---

Scanners/Series/Absolute Series Scanner.py

```
Oct 27, 2018 16:42:51.779 [1120] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
File "C:\Users\JayXon\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 472, in Scan
set_logging(foldername=PLEX_LIBRARY[root] if root in PLEX_LIBRARY else '', filename=log_filename+'.filelist.log', mode='w') #add grouping folders filelist
File "C:\Users\JayXon\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 219, in set_logging
if os.sep=="\\":  LOG_FILE = winapi_path(LOG_FILE) # Bypass DOS path MAX_PATH limitation
File "C:\Users\JayXon\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 201, in winapi_path
if path.startswith(u"\\\\"):  return u"\\\\?\\UNC\\" + path[2:] …
```

Fix crash for non english path

---

Scanners/Series/Absolute Series Scanner.py

As discussed [#243]; this allows the scanner to fallback from forced `[anidb2/3/4]` modes back to `[anidb]` mode when there is no tvdb match.
The idea here is to prevent `[tvdb-]` entries which would end up being merged by Plex under a single entry.
PR has been tested with a library of under `[anidb3]` mode with a few temporary entries under `[anidb2]` mode.
`[anidb4]` mode should behave exactly as `[anidb3]` mode but there have been no tests under `[tvdb/2/3/4]` modes (which this PR doesn't touch).
So far I haven't seen any side-effects but please review before merging.
---

[anidb2/3/4] mode fallback to [anidb] if tvdb match fails

---

Scanners/Series/Absolute Series Scanner.py

Fix for #267. Fixed scanner to correctly detect movie files.
- remove requirement for "- Complete Movie" file to be in root folder
- also match if only file in folder and "movie" or "gekijouban" is in filename or folder
Signed-off-by: KuroSetsuna29 <jamc29@gmail.com>

Fix for #267. Fixed scanner to correctly detect movie files.

---

Scanners/Series/Absolute Series Scanner.py

Currently for youtube channels (UC) the seasons and episode order are set\ordered by file modification date.    On my system I have numerous files where the modification date is wrong for one reason or another and episodes are in the wrong seasons or in the wrong order.
When downloading the channel, I begin all filenames with yyyymmdd - * so the information to order the files is already in the filename.  I modified the scanner to order files by filename and then extract the season from the date in the filename.
Other than the sorting change, I believe all other edits should be transparent to users that don't follow this naming convention - but to ensure it wouldn't affect users unintentionally I tied the new behavior to an option boolean and defaulted it to off.  As I know some start …

Add ability for youtube channel seasons and episode order be specified by filename date

---

anime-list-corrections.xml

The previous TVDB ID was for an old show with the same name, this one matches the AniDB ID

TVDB ID for Ikebukuro West Gate Park

---

Scanners/Series/Absolute Series Scanner.py

Previously, if a title contained the word containing the substring "omake", it would be treated as a special. Now this only happens if the "omake" substring does not have letters before and after it. I tested with an episode of a show titled "S02E23 - Videomakers.mkv", before this commit it was put in Season 0, after it's put in Season 2.

Match titles containing 'omake' as specials only if it's the whole word

---

README.md

Previous one was leading to 404 page

Update Plex Support URL for .plexignore files

---

Scanners/Series/Absolute Series Scanner.py

- Move encoding / decoding before exists check.
- Prevent that the directory isn't further scanned if exists check fails.
This fixed #353 for me, the `except`  message isn't logged, so most likely the necessary fix was the encoding before checking.
Log result:
Test2.scanner.log
```
=============================================================================================================================================================
Call: "Plex", path: "Test2", folder_show: "Test2", dirs (0), files (3)
=============================================================================================================================================================
"Test2" s01e         4                         "Word Search" "Entführt" "Fullmetal Panic! - 04 - Entführt.mkv"
"Test2" s01e …
```

Encode filename before checking existence, Fix #353

---

Scanners/Series/Absolute Series Scanner.py

On my OS (freebsd), I noticed that there is no env variable named PLEXTOKEN. There is however an X-PLEX-TOKEN. This change checks for the existence of an X-Plex-Token.id file and uses its content (these are instructions provided on the readme) and uses that instance.
A simpler change would be to check for an OS environment variable named X-PLEX-TOKEN if that is common across environments, but I dont know whats more common and this might be the least disruptive change.

Prefer content of X-Plex-Token.id file over env variable

---

Scanners/Series/Absolute Series Scanner.py

This PR fixes a issue that [Line 434](https://github.com/ZeroQI/Absolute-Series-Scanner/compare/master...ZigZagT:master#diff-7da0de522f8dd1b3ff90ff42b22f0289b075d66b6d154a6b4394a5ab61207b13R434) can sometimes throw UnicodeError due to OS default encoding isn't set to utf-8 (namely in the official plex docker image)

fix encoding error

---

Scanners/Series/Absolute Series Scanner.py

Supports additional #episodes format. Here are a few examples:
```
my show [第1話] [1920x1080].mp4
my show [第1-3話] [1920x1080].mp4
```
This format exists in Japanese language environment. I assume the support of this format makes sense since animes are mostly Japanese made.
Since the change involves using unicode in the regex, I've to changed all `r'<regex>'` to `ur'<regex>'` to make things work. (non unicode re object in python2 doesn't handle unicode match)

support more #episodes format

---

Scanners/Series/Absolute Series Scanner.py

Fixes #397 
If specials contained an alphabetical character (i.e. 2a / 2b), the script would perform a string / integer comparison which could throw off the `cumulative_offset` (for example, `2 < '1' == true`).
This fixes this so that the variable `ep` is always an integer value when being compared in the initialisation of `cumulative_offset`.

Fixes a bug in specials ordering for forced 'anidb'

---

Scanners/Series/Absolute Series Scanner.py

Noticed an issue with [YouTube-Agent](https://github.com/ZeroQI/YouTube-Agent.bundle) where videos with the same upload date (e.g. [U_SM507Q-aU)](https://www.youtube.com/watch?v=U_SM507Q-aU) and [uKmQTE8iYqI](https://www.youtube.com/watch?v=uKmQTE8iYqI)) wouldn't have any metadata in Plex.
There's an error in the YouTube-Agent logs:
```
2022-03-12 13:08:34,957 (7f0fdb920b38) :  CRITICAL (agentkit:1095) - Exception in the update function of agent named 'YouTubeSeries', called with guid 'com.plexapp.agents.youtube://youtube|UCU7iRrk3xfpUk0R6VdyC1Ow|NBA on TNT [UCU7iRrk3xfpUk0R6VdyC1Ow]/2022/1900-01-01?lang=xn' (most recent call last):
File "/usr/lib/plexmediaserver/Resources/Plug-ins-c8bd13540/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1093, in …
```

Trim dupe index from episode

---

Scanners/Series/Absolute Series Scanner.py

#375 Ignored the VIDEO_TS and BDMV directories broke the scanning of BDMV format media.

Fix: Scanning BDMV Format Media

---

Scanners/Series/Absolute Series Scanner.py

Fix: Scanner does not work when the file name is full of brackets

---

README.md
Scanners/Series/Absolute Series Scanner.py

Took a stab at altering to provide further support for channels that may release multiple episodes on a given day, so it plays nicer with the Youtube agent. The constructed episode numbers allow the episodes to remain unique and the Meta Agent to correctly pull and apply metadata to the episodes. The 8 digit episode numbers are certainly more unsightly than the episodes being displayed by date, but supplies "better" functionality in the given circumstance.
Still not 100% duplicate proof as you could end up with two episodes on the same day that managed to also be modified within the same minute. However the likelihood of this seems lower than the probability that the current implementation fails (due to Plex limitations).
Felt using the Hour/Minute as an "index" provided more robustness …

Youtube2 switch for same date episode handling

---

Scanners/Series/Absolute Series Scanner.py

When E01 and E10 were present (and E02 and E20, etc.) along with DD2.0 and 1080p the episode number parser would report E10 (and E20, etc.) as E01 (and E02, etc.).  This caused "Episode 1" to have two versions that were actually E01 and E10, and the same for "Episode 2" and so on.
This change just follows the pattern of cleaning up predictable parts of file names that cause problems when extracting the episode number.
Closes #428

Remove "DD2.0" to prevent Ex0 being handled as E0x

---

Scanners/Series/Absolute Series Scanner.py

when an episode title has `S\d+ - ` in it, that shouldn't be detected as a special when it is actually marking the season

fix detecting Sxxx as episode title and marking it as a special when it is followed by a separator

---

Scanners/Series/Absolute Series Scanner.py

this allows the equivalent detection of the forced id file as the name of the folder when overriding default behaviour

lets forced if file have the same override priority as a folder name

---

Scanners/Series/Absolute Series Scanner.py

since we are likely to want to know what the full path is if digging through logs, and the ignore uses the real folder name

makes log of folder use the full name, not cleaned name

---

Scanners/Series/Absolute Series Scanner.py

#459 fixed matching `S2 - 02` as special 2 instead of episode 2, but we didn't keep advancing in the string when this happens.
if we don't have enough word matches due to small amount of files, then some specials in later seasons like `S2 - S5`
this makes it continue checking the rest of the words for a valid match

fix not checking the rest of the string when skipping a season in word search

---

tvdb4.mapping.xml

Sourced from https://kimetsu-no-yaiba.fandom.com/wiki/Story_Arcs
Was on the fence between bundling the first season as `Unwavering Resolve Arc` instead of breaking it into sub-arcs. Thoughts?
```
01|001|005|Final Selection Arc
02|006|007|Kidnapper's Bog Arc
03|008|010|Asakusa Arc
04|011|014|Tsuzumi Mansion Arc
05|015|021|Mount Natagumo Arc
06|022|026|Rehabilitation Training Arc
07|027|033|Mugen Train Arc
08|034|044|Entertainment District Arc
09|045|055|Swordsmith Village Arc
10|056|056|Hashira Training Arc (unknown length)
```

Demon slayer arcs

---

Scanners/Series/Absolute Series Scanner.py

I believe this fixes #478. I tested this on my local plex media server editing and am now able to observe the scanner pick up my new anime episodes. The `Plex Media Scanner.log` no longer logs messages like
```
ERROR - No module in Absolute Series Scanner
```

fix missing parens

---

Scanners/Series/Absolute Series Scanner.py

I came across the behavior in [this comment](https://github.com/ZeroQI/Absolute-Series-Scanner/issues/70#issuecomment-269631474) which [seemed to me like a regression](https://github.com/ZeroQI/Absolute-Series-Scanner/issues/70#issuecomment-2041790439).  This change fixes it, but I wasn't quite sure if it was the most appropriate way.

Treat OAD as Specials

---

.vscode/extensions.json
Scanners/Series/Absolute Series Scanner.py

This will allow users to use either `[anidb-16418]` or `{anidb-16418}` in folder names.

Add compatibility with Plex Series and Movie scanner folder-id format.

---

Scanners/Series/Absolute Series Scanner.py

Very short strings could be removed from somewhere they shouldn't. This has the potential to break things. For example, if a zero ended up in misc_words, it could break the part of the string representing the season and episode. "S01E01" would become "S 1E 1" This won't match any regex looking for season/episode.

Make sure items to remove are delimited

---

Scanners/Series/Absolute Series Scanner.py

Reverts ZeroQI/Absolute-Series-Scanner#506
The original commit introduced a regression that breaks handling for all file paths containing non-ASCII characters (e.g., Chinese characters).
This issue occurs because the Plex binary executes within its own embedded Python 2.7 environment, and the changes in the original commit are incompatible with it, causing file paths to be processed incorrectly. This leads to widespread misidentification of media files.
Reverting this change is necessary to restore functionality for users with international or special characters in their file names.

Revert "Update regex syntax for python3"
