ZeroQI/Absolute-Series-Scanner

Scanners/Series/Absolute Series Scanner.py
Image from https://hub.docker.com/r/linuxserver/plex/
=> Docker linuxserver/plex folder path for Logs added

Scanners/Series/Absolute Series Scanner.py
=> Fix 'clean_string' parenthesis behavior

Scanners/Series/Absolute Series Scanner.py
Fix parenthesis behavior per issue #30
Additional behavior arguments of 'no_whack' (skip pre_whack/whack) & 'no_dash' (remove '-' characters)
=> Fix/Enhance 'clean_string' function

Scanners/Series/Absolute Series Scanner.py
```
##################################################
Scanner mode "tvdb4" (Custom Seasons):
##################################################
Option 1
Define season folders and place episode files in the season folder wanted.
Requirement(s): Episode numbers must be numbered as their absolute numbering
##################################################
Option 2
Define season folders in a mapping file and place episode files in the main series folder.
Requirement(s):
(1) Episode numbers must be numbered as their absolute numbering
(2) Mapping file must be defined locally in the series folder
FORMAT:
[season_num]|[starting_ep_num]|[ending_ep_num]|[freeform_text_naming_the_season](optional)
EX:
01|001|012|Vampire Reign 
02|013|024|Battle in Nagoya …
```
=> TVDB4 mode addition

Scanners/Series/Absolute Series Scanner.py
Further code reduction [down to 407 lines]:
. removed seasonsfromfolder file
. removed zerofilesize file
. abs_manual_placement_worked replaced by else
. urrlib python 3 included
=> Code reduction

Scanners/Series/Absolute Series Scanner.py
- TVDB modes season & ep offset
- "anidb2" mode for automatic scudlee offset
- "rawgit.com" url update
- Static variable CAPS
- Update for log rotation & persistent file handle
- Log level additions
=> Multiple Updates

Scanners/Series/Absolute Series Scanner.py
<anime anidbid="10376" tvdbid="259640" defaulttvdbseason="2">
<name>Sword Art Online II</name>
<mapping-list>
<mapping anidbseason="0" tvdbseason="0" start="1" end="10" offset="11"/>
</mapping-list>
</anime>
"ERROR - anidbTvdbMapping() - mappingList creation exception" in logs....
=> anidbTvdbMapping() mappingList exception

Scanners/Series/Absolute Series Scanner.py
season 2 strike witches not appearing on PMS 1.2.7
trying to uniformise the serie name
=> anidb2 common serie title

Scanners/Series/Absolute Series Scanner.py
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/85
=> Fix parsing root folder files

anime-list-corrections.xml
@ZeroQI please confirm (merge) or not. These were added in your initial upload. It looks like they are either incorrect or out-of-date?
9227 doesn't even look correct as is in the ASS file. (EX: ";15-16;16-16;")
Current ScudLee:
```xml
<anime anidbid="9227" tvdbid="262098" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
<name>Girls und Panzer</name>
<mapping-list>
<mapping anidbseason="0" tvdbseason="0">;2-9;3-2;4-10;5-15;6-20;7-24;8-28;9-3;10-11;11-16;12-21;13-25;14-29;15-501;16-502;17-7;18-17;19-22;20-26;21-6;22-18;23-32;24-4;25-12;26-19;27-9;28-13;29-27;30-5;31-14;32-23;33-33;34-30;35-31;</mapping>
</mapping-list>
</anime>
<anime anidbid="10009" tvdbid="262098" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
<name>Girls und Panzer: Kore ga Hontou no Anzio-sen …
```
=> Remove persisted changes

Scanners/Series/Absolute Series Scanner.py
Added an SSL context to `urlopen`
=> Add SSL context - master

Scanners/Series/Absolute Series Scanner.py
Added an SSL context to `urlopen`
=> Add SSL context - beta

tvdb4.mapping.xml
Changed to accurately reflect the conclusion of Dragon Ball Super and corrected season numbering/episodes to match TVDB/Wikipedia seasons
=> Fix Dragon Ball Super

Scanners/Series/Shell Update scanner.sh
Just thought I'd commit one for Linux/macOS since there is a PowerShell script for Windows just to match.
=> Add Shell script to update ASS for Linux/macOS

Scanners/Series/Absolute Series Scanner.py
@ZeroQI, Setup for easy merge if ok
=> Update to 'SOURCE_ID' parsing

Scanners/Series/Absolute Series Scanner.py
Hi @ZeroQI
1. The Season/Episode offset setup can now be used for all 'anidb*' & 'tvdb*' source ids
2. The Episode offset setup can now handle negative numbers. So a 'e-12' id entry can be used to take an 'e13' down to an 'e1'
3. We now have a reusable 'download_and_read_file' function for caching files into the runtime tmp folder
4. Regex overhaul/reduction for faster scans
Updates are broken apart into the below 14 commits for you to more easily see what was changed and why.
=> Major Updates

Scanners/Series/Absolute Series Scanner.py
Hi @ZeroQI,
-- Cache: Add TVDB json & Store AniDB uncompressed
-- Logging updates
-- Outsource 'COUNTER' to a global variable
-- Fixes for 'anidb2' mapping & id offset issues
=> Cache Updates & Mapping Fixes

Scanners/Series/Absolute Series Scanner.py
Hello @ZeroQI 
The pattern was looking on matches char by char instead of lines by lines.
I fixed it with minimum refacto, with a variable for lisibility.
=> Fixed pattern matching. It was looping on char instead of lines.

Scanners/Series/Absolute Series Scanner.py
Hi @ZeroQI,
Updates are broken down into commits.
I think I've hit the last I can fix/tweak for the current scanner. 😄 
`Update "File main loop"`:
Reason for this was this instance I had below. I have 4 different copies of episode 1 so '01' was in 'misc_words'. Thus it was filtered out of the filename so all episodes had no episode number and all were being hit as s0e5XX.
```
=============================================================================================================================================================
Forced ID (series folder) - source: "tvdb", id: "303867-s1e11"
offset_season = 0, offset_episode = 10
------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Scanner Updates

Scanners/Series/Absolute Series Scanner.py
=> Fix encodeASCII() result not being used

Scanners/Series/Absolute Series Scanner.py
Updated path to youtube API key in com.plexapp.agents.youtube.xml
=> Scanner not using user defined API key if set.

Scanners/Series/Absolute Series Scanner.py
Tied to https://github.com/ZeroQI/Hama.bundle/pull/374
=> Multiple Enhancements

Scanners/Series/Absolute Series Scanner.py
Missing DD2.1 from usually netflix anime releases.
=> Update Absolute Series Scanner.py

Scanners/Series/Absolute Series Scanner.py
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/262
=> Filebot Xattr support attempt

tvdb4.posters.xml
The old poster link didn't work. I updated it with the new picture the wiki is using for that arc.
=> Fix Broken HxH Poster

Scanners/Series/Absolute Series Scanner.py
the dirs is a `list`, can't remove the item in it when iteration
=> fix: iterate the dir list and remove item

tvdb4.mapping.xml, tvdb4.posters.xml
Added tvdb4 mapping for JoJo and set posters. Set as ongoing as future proofing for the eventual part 6
=> JoJo's Bizarre Adventure

anime-list-corrections.xml
The offset for S5 ending and S6 beginning was 1 episode off
=> Fix InuYasha S5-S6 offset

Scanners/Series/Absolute Series Scanner.py
Escape Regex Characters in path
=> Escape Regex Characters in path

Scanners/Series/Absolute Series Scanner.py
Changeover from ScudLee anime-lists, which has fallen behind. Switch to new repo that is being actively maintained.
Updating per https://github.com/ZeroQI/Absolute-Series-Scanner/issues/315 and https://github.com/ZeroQI/Hama.bundle/issues/433
=> Anime-Lists Update

Scanners/Series/Absolute Series Scanner.py
Unicode paths are used consistently internally. They are only converted to 'utf-8' or filesystem default encoding as needed when giving out to Plex.
This should fix #306 and #335.
=> Properly handle unicode file paths

Scanners/Series/Absolute Series Scanner.py
=> removing redundant spaces

Scanners/Series/Absolute Series Scanner.py
Fix for any issues regarding .plexignore file not behaving the way it would have if you were using the standard Plex file scanner. Fixes the issues in #374 allowing directories to be ignored. The code is heavily commented explaining why it was coded that way. There are remnants of the old system lingering in the remaining code and the way that the root scanner log displays the list of directories is odd.
=> Rewrote the code for ignored directories and files, plexignore and filtering

tvdb4.mapping.xml, tvdb4.posters.xml
more accurate sagas for dragon ball z
=> Update tvdb4 mapping and posters - Dragon Ball Z

Scanners/Series/Absolute Series Scanner.py
Ex: [VCB-Studio&AI-Raws] slamdunk [23v2][Ma10p_1080p][x265_flac]
=> Fix different versions of the ep being mapped to special. Ex: [23v2]

Scanners/Series/Absolute Series Scanner.py
1. Support special folder name: SPs and 映像特典
2. Support OPED and OVA inside the brackets. Ex.[NCOP01],[OVA01]
3. Add some WHACK_PRE_CLEAN_RAW words.
=> Enhanced identification of special files

Scanners/Series/Absolute Series Scanner.py
If a directory contains special characters like `[`, `]` or `?` in its name, then the match would be incorrect and would even panic in python2 (with patterns like `[c-a]`), making `.plexignore` not usable.
The polyfill is modified from `fnmatch` in python2. I removed the branch for `[` and `?` since they're not defined in `plexignore` specification.
=> implement fnmatch polyfill

Scanners/Series/Absolute Series Scanner.py
was checking folder_clean, which explicitly removes some of the text to match ignore values
=> fix checking ignore

Scanners/Series/Absolute Series Scanner.py
missed this line in the comparison...
=> add missing variable initialisation for #464

tvdb4.mapping.xml, tvdb4.posters.xml
- Addition of season 26 (Egg Head Island)
=> Update one piece mapping for tvdb4

Scanners/Series/Absolute Series Scanner.py
=> Update regex syntax for python3

Scanners/Series/Absolute Series Scanner.py
=> Moved parentheses in Playlist.info.json handling code
